[package]
name = "hikami"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "warn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = { version = "0.7.2", default-features = false }
fdt = "0.1.5"
panic-halt = "0.2.0"
riscv = "0.10.1"
riscv-rt = "0.11.0"
spin = "0.9.8"
wild_screen_alloc = { version = "0.1.1",  path = "wild-screen-alloc" }
