[package]
name = "hikami"
version = "1.2.0"
edition = "2021"

[lints.clippy]
pedantic = "warn"
missing_docs_in_private_items = "warn"

[lints.rust]
missing_docs = "warn"

[lints.rustdoc]
missing_crate_level_docs = "warn"

[profile.release]
panic = 'abort'
codegen-units = 1

[workspace]
members = [ "extension_manager" , "hikami_core"]

[workspace.dependencies]
elf = { version = "0.7.2", default-features = false }
fdt = "0.1.5"
linked_list_allocator = "0.10.5"
raki = { git = "https://github.com/Alignof/raki", branch = "feature/Zbb"}
riscv = "0.11.1"
rustsbi = "0.4.0"
sbi-rt = "0.0.3"
sbi-spec = { version = "0.0.8", features = [ "legacy" ] }
spin = "0.9.8"

[features]
# debug log
debug_log = [ "hikami_core/debug_log" ]
# identity memory map
identity_map = [ "hikami_core/identity_map" ]
# default on
default = [ "enable_extension" ]
# for `extension_manager`
enable_extension = [ "hikami_zbb" ]

[dependencies]
hikami_core = { path = "hikami_core" }
hikami_zbb = { git = "https://github.com/Alignof/hikami_zbb", branch = "develop", optional = true }
extension_manager = { path = "extension_manager" }

elf = { workspace = true }
fdt = { workspace = true }
raki = { workspace = true }
riscv = { workspace = true }
rustsbi = { workspace = true }
sbi-rt = { workspace = true }
sbi-spec = { workspace = true }
linked_list_allocator = { workspace = true }

[patch.'https://github.com/Alignof/hikami']
hikami_core = { path = "hikami_core" }
