[package]
name = "hikami"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hikami"
path = "src/init.rs"

[dependencies]
fdt = "0.1.5"
panic-halt = "0.2.0"
riscv = "0.10.1"
riscv-rt = "0.11.0"
