[target.riscv64imac-unknown-none-elf]
runner = """
qemu-system-riscv64
-cpu rv64,smstateen=true
-machine virt
-bios default
-nographic
-m 2G
-drive file=rootfs.ext2,format=raw,id=hd0,if=none
-device ich9-ahci,id=ahci -device ide-hd,drive=hd0,bus=ahci.0 
-kernel
"""

# With IOMMU
# runner = """
# qemu-system-riscv64
# -cpu rv64,smstateen=true
# -machine virt
# -bios default
# -nographic
# -m 2G
# -drive file=rootfs.ext2,format=raw,id=hd0,if=none
# -device virtio-blk-pci,drive=hd0,iommu_platform=true,disable-legacy=on
# -netdev user,id=n1
# -device virtio-net-pci,netdev=n1,iommu_platform=true,disable-legacy=on
# -append root=/dev/vda,rw,console=ttyS0
# -device riscv-iommu-pci
# -kernel
# """

# for debug
# runner = "../../qemu/build/qemu-system-riscv64 -S -gdb tcp::10000 -d int,in_asm,cpu_reset,mmu,page,guest_errors -machine virt -bios none -nographic -m 2G -initrd vmlinux_debug -drive file=rootfs.img,format=raw,id=hd0,if=none -device virtio-blk-pci,drive=hd0,iommu_platform=true,disable-legacy=on -append root=/dev/vda,rw,console=ttyS0 -device riscv-iommu-pci -kernel"
# memo: maintenance packet Qqemu.PhyMemMode:1

rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "target-feature=+h",
]

[build]
target = "riscv64imac-unknown-none-elf"
