[package]
name = "extension_manager"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[build-dependencies]
serde_json = "1.0.138"

[dependencies]
quote = "1.0.38"
syn = "2.0.98"
proc-macro2 = "1.0.93"
