name: Rust

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_INCREMENTAL: 0

# Copyright (c) 2021 sksat
# https://github.com/sksat/action-clippy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable # Rustup toolchain specifier e.g. stable, nightly, 1.42.0, nightly-2022-01-01. 
          target: riscv64imac-unknown-none-elf # Comma-separated string of additional targets to install e.g. wasm32-unknown-unknown
          components: clippy, rustfmt

      - uses: sksat/action-clippy@v0.7.0
        if: github.event_name == 'push'
        with:
          reporter: github-check

      - uses: sksat/action-clippy@v0.7.0
        if: github.event_name == 'pull_request'
        with:
          reporter: github-pr-review

      - name: format check 
        run: cargo fmt --all -- --check
      
      # no crate for test in no_std
      #- name: unit test
      #  run: cargo test

