name: Rust

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_INCREMENTAL: 0

# Copyright (c) 2021 sksat
# https://github.com/sksat/action-clippy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install clippy
        uses: dsherret/rust-toolchain-file@v1

      - name: create dummy file
        run: |
          touch vmlinux
          touch initrd
          touch guest.dtb
          echo '#!/bin/sh' > dtc && chmod +x dtc && mv dtc /usr/local/bin/dtc

      - uses: sksat/action-clippy@v1.0.0
        if: github.event_name == 'push'
        with:
          reporter: github-check

      - uses: sksat/action-clippy@v1.0.0
        if: github.event_name == 'pull_request'
        with:
          reporter: github-pr-review

      - name: format check 
        run: cargo fmt --all -- --check
      
      # no crate for test in no_std
      #- name: unit test
      #  run: cargo test

